name: Publish to TestPyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build wheel and sdist
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
        env:
          # Create this in your repo's Settings > Secrets and variables > Actions
          # Name: TESTPYPI_API_TOKEN, Value: pypi-AgENdGVzdC5weXBpLm9yZwIk...
          PYPI_API_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
